apiVersion: apps/v1
kind: Deployment 
metadata:
  name: python-pod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      name: pythonpod
      labels:       
        app: python              
    spec:
      containers:
      - image: avinashdabhade/papp      
        name: mypythonapp
---                                
apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: NodePort 
  selector:                        
    app: python                
  ports:
  - port: 5000
    