apiVersion: apps/v1
kind: Deployment 
metadata:
  name: springboot-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      name: springpod
      labels:       
        app: spring              
    spec:
      containers:
      - image: avinashdabhade/first-springboot-app      
        name: springboot-app
---                                
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort 
  selector:                        
    app: spring                
  ports:
  - port: 80
    targetPort: 8080